# Generated by Django 4.2.9 on 2024-01-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_tagpost_alter_women_cat_women_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='tag',
            new_name='tags',
        ),
    ]
