# Generated by Django 4.2.9 on 2024-01-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_husband_women_husband'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
